// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: screen

#include "../include/ui.h"

void ui_auton_selector_screen_init(void)
{
    ui_auton_selector = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_auton_selector, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_page_selector = lv_obj_create(ui_auton_selector);
    lv_obj_remove_style_all(ui_page_selector);
    lv_obj_set_width(ui_page_selector, 30);
    lv_obj_set_height(ui_page_selector, 240);
    lv_obj_set_x(ui_page_selector, -225);
    lv_obj_set_y(ui_page_selector, 0);
    lv_obj_set_align(ui_page_selector, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page_selector, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_page_selector, lv_color_hex(0x450077), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_selector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_button = lv_btn_create(ui_page_selector);
    lv_obj_set_width(ui_debug_button, 20);
    lv_obj_set_height(ui_debug_button, 20);
    lv_obj_set_x(ui_debug_button, 0);
    lv_obj_set_y(ui_debug_button, 105);
    lv_obj_set_align(ui_debug_button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_debug_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_debug_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_debug_button, &ui_img_debug_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_debug_button, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_img_create(ui_page_selector);
    lv_img_set_src(ui_logo, &ui_img_steamed_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo, 0);
    lv_obj_set_y(ui_logo, -105);
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_team_number = lv_label_create(ui_page_selector);
    lv_obj_set_width(ui_team_number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_team_number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_team_number, 0);
    lv_obj_set_y(ui_team_number, -85);
    lv_obj_set_align(ui_team_number, LV_ALIGN_CENTER);
    lv_label_set_text(ui_team_number, "8757B");
    lv_obj_set_style_text_color(ui_team_number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_team_number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_team_number, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auton_button = lv_btn_create(ui_page_selector);
    lv_obj_set_width(ui_auton_button, 20);
    lv_obj_set_height(ui_auton_button, 20);
    lv_obj_set_x(ui_auton_button, 0);
    lv_obj_set_y(ui_auton_button, 80);
    lv_obj_set_align(ui_auton_button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_auton_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_auton_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_auton_button, &ui_img_auton_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_auton_button, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alliance_switch = lv_switch_create(ui_auton_selector);
    lv_obj_set_width(ui_alliance_switch, 50);
    lv_obj_set_height(ui_alliance_switch, 25);
    lv_obj_set_x(ui_alliance_switch, -180);
    lv_obj_set_y(ui_alliance_switch, -103);
    lv_obj_set_align(ui_alliance_switch, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_alliance_switch, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_alliance_switch, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alliance_switch, lv_color_hex(0x830000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alliance_switch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alliance_switch, lv_color_hex(0x1C0088), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_alliance_switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_radius(ui_alliance_switch, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_alliance_label = lv_label_create(ui_auton_selector);
    lv_obj_set_width(ui_alliance_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alliance_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_alliance_label, 91);
    lv_obj_set_y(ui_alliance_label, 9);
    lv_label_set_text(ui_alliance_label, "Red Alliance");

    ui_auton_1_btn = lv_btn_create(ui_auton_selector);
    lv_obj_set_width(ui_auton_1_btn, 50);
    lv_obj_set_height(ui_auton_1_btn, 50);
    lv_obj_set_x(ui_auton_1_btn, -180);
    lv_obj_set_y(ui_auton_1_btn, -58);
    lv_obj_set_align(ui_auton_1_btn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_auton_1_btn, lv_color_hex(0x450077), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_auton_1_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auton_2_btn = lv_btn_create(ui_auton_selector);
    lv_obj_set_width(ui_auton_2_btn, 50);
    lv_obj_set_height(ui_auton_2_btn, 50);
    lv_obj_set_x(ui_auton_2_btn, -180);
    lv_obj_set_y(ui_auton_2_btn, -3);
    lv_obj_set_align(ui_auton_2_btn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_auton_2_btn, lv_color_hex(0x450077), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_auton_2_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auton_3_btn = lv_btn_create(ui_auton_selector);
    lv_obj_set_width(ui_auton_3_btn, 50);
    lv_obj_set_height(ui_auton_3_btn, 50);
    lv_obj_set_x(ui_auton_3_btn, -180);
    lv_obj_set_y(ui_auton_3_btn, 52);
    lv_obj_set_align(ui_auton_3_btn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_auton_3_btn, lv_color_hex(0x450077), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_auton_3_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auton_1_label = lv_label_create(ui_auton_selector);
    lv_obj_set_width(ui_auton_1_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auton_1_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auton_1_label, -181);
    lv_obj_set_y(ui_auton_1_label, -58);
    lv_obj_set_align(ui_auton_1_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auton_1_label, "1");

    ui_auton_2_label = lv_label_create(ui_auton_selector);
    lv_obj_set_width(ui_auton_2_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auton_2_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auton_2_label, -181);
    lv_obj_set_y(ui_auton_2_label, -2);
    lv_obj_set_align(ui_auton_2_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auton_2_label, "2");

    ui_auton_3_label = lv_label_create(ui_auton_selector);
    lv_obj_set_width(ui_auton_3_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_auton_3_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_auton_3_label, -181);
    lv_obj_set_y(ui_auton_3_label, 51);
    lv_obj_set_align(ui_auton_3_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_auton_3_label, "3");

    ui_selected_auton = lv_label_create(ui_auton_selector);
    lv_obj_set_width(ui_selected_auton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_selected_auton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_selected_auton, -3);
    lv_obj_set_y(ui_selected_auton, -4);
    lv_obj_set_align(ui_selected_auton, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_selected_auton, "Debug Selected");

    lv_obj_add_event_cb(ui_debug_button, ui_event_debug_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_auton_button, ui_event_auton_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alliance_switch, ui_event_alliance_switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_auton_1_btn, ui_event_auton_1_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_auton_2_btn, ui_event_auton_2_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_auton_3_btn, ui_event_auton_3_btn, LV_EVENT_ALL, NULL);

}
