// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: screen

#include "../include/ui.h"

void ui_debug_screen_init(void)
{
    ui_debug = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_debug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_debug);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "DEBUG");

    ui_page_selector2 = lv_obj_create(ui_debug);
    lv_obj_remove_style_all(ui_page_selector2);
    lv_obj_set_width(ui_page_selector2, 30);
    lv_obj_set_height(ui_page_selector2, 240);
    lv_obj_set_x(ui_page_selector2, -225);
    lv_obj_set_y(ui_page_selector2, 0);
    lv_obj_set_align(ui_page_selector2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_page_selector2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_page_selector2, lv_color_hex(0x450077), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_page_selector2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug_button2 = lv_btn_create(ui_page_selector2);
    lv_obj_set_width(ui_debug_button2, 20);
    lv_obj_set_height(ui_debug_button2, 20);
    lv_obj_set_x(ui_debug_button2, 0);
    lv_obj_set_y(ui_debug_button2, 105);
    lv_obj_set_align(ui_debug_button2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_debug_button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_debug_button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_debug_button2, &ui_img_debug_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_debug_button2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo2 = lv_img_create(ui_page_selector2);
    lv_img_set_src(ui_logo2, &ui_img_steamed_png);
    lv_obj_set_width(ui_logo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo2, 0);
    lv_obj_set_y(ui_logo2, -105);
    lv_obj_set_align(ui_logo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_team_number2 = lv_label_create(ui_page_selector2);
    lv_obj_set_width(ui_team_number2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_team_number2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_team_number2, 0);
    lv_obj_set_y(ui_team_number2, -85);
    lv_obj_set_align(ui_team_number2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_team_number2, "8757B");
    lv_obj_set_style_text_color(ui_team_number2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_team_number2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_team_number2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_auton_button2 = lv_btn_create(ui_page_selector2);
    lv_obj_set_width(ui_auton_button2, 20);
    lv_obj_set_height(ui_auton_button2, 20);
    lv_obj_set_x(ui_auton_button2, 0);
    lv_obj_set_y(ui_auton_button2, 80);
    lv_obj_set_align(ui_auton_button2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_auton_button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_auton_button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_auton_button2, &ui_img_auton_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_auton_button2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_debug_button2, ui_event_debug_button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_auton_button2, ui_event_auton_button2, LV_EVENT_ALL, NULL);

}
