// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: screen

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_auton_selector
void ui_auton_selector_screen_init(void);
lv_obj_t * ui_auton_selector;
lv_obj_t * ui_page_selector;
void ui_event_debug_button(lv_event_t * e);
lv_obj_t * ui_debug_button;
lv_obj_t * ui_logo;
lv_obj_t * ui_team_number;
void ui_event_auton_button(lv_event_t * e);
lv_obj_t * ui_auton_button;
void ui_event_alliance_switch(lv_event_t * e);
lv_obj_t * ui_alliance_switch;
lv_obj_t * ui_alliance_label;
void ui_event_auton_1_btn(lv_event_t * e);
lv_obj_t * ui_auton_1_btn;
void ui_event_auton_2_btn(lv_event_t * e);
lv_obj_t * ui_auton_2_btn;
void ui_event_auton_3_btn(lv_event_t * e);
lv_obj_t * ui_auton_3_btn;
lv_obj_t * ui_auton_1_label;
lv_obj_t * ui_auton_2_label;
lv_obj_t * ui_auton_3_label;
lv_obj_t * ui_selected_auton;


// SCREEN: ui_debug
void ui_debug_screen_init(void);
lv_obj_t * ui_debug;
lv_obj_t * ui_Label3;
lv_obj_t * ui_page_selector2;
void ui_event_debug_button2(lv_event_t * e);
lv_obj_t * ui_debug_button2;
lv_obj_t * ui_logo2;
lv_obj_t * ui_team_number2;
void ui_event_auton_button2(lv_event_t * e);
lv_obj_t * ui_auton_button2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_debug_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_debug, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_debug_screen_init);
    }
}
void ui_event_auton_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_auton_selector, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_auton_selector_screen_init);
    }
}
void ui_event_alliance_switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_alliance_label, _UI_LABEL_PROPERTY_TEXT, "Blue Alliance");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_alliance_label, _UI_LABEL_PROPERTY_TEXT, "Red Alliance");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        alliance_changed(e);
    }
}
void ui_event_auton_1_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        auton_1_selected(e);
        _ui_label_set_property(ui_selected_auton, _UI_LABEL_PROPERTY_TEXT, "Left Close Goal Selected");
    }
}
void ui_event_auton_2_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        auton_2_selected(e);
        _ui_label_set_property(ui_selected_auton, _UI_LABEL_PROPERTY_TEXT, "Right Close Goal Selected");
    }
}
void ui_event_auton_3_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        auton_3_selected(e);
        _ui_label_set_property(ui_selected_auton, _UI_LABEL_PROPERTY_TEXT, "Wall Stake Selected");
    }
}
void ui_event_debug_button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_debug, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_debug_screen_init);
    }
}
void ui_event_auton_button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_auton_selector, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_auton_selector_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_auton_selector_screen_init();
    ui_debug_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_auton_selector);
}
