// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: screen

#include "ui.h"
#include "auton.h"

void alliance_changed(lv_event_t * e)
{
	alliance *= -1;
}

void auton_1_selected(lv_event_t * e)
{
	selected_auton = 1;
}

void auton_2_selected(lv_event_t * e)
{
	selected_auton = 2;
}

void auton_3_selected(lv_event_t * e)
{
	selected_auton = 3;
}
