// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: screen

#ifndef _SCREEN_UI_H
#define _SCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "liblvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_auton_selector
void ui_auton_selector_screen_init(void);
extern lv_obj_t * ui_auton_selector;
extern lv_obj_t * ui_page_selector;
void ui_event_debug_button(lv_event_t * e);
extern lv_obj_t * ui_debug_button;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_team_number;
void ui_event_auton_button(lv_event_t * e);
extern lv_obj_t * ui_auton_button;
void ui_event_alliance_switch(lv_event_t * e);
extern lv_obj_t * ui_alliance_switch;
extern lv_obj_t * ui_alliance_label;
void ui_event_auton_1_btn(lv_event_t * e);
extern lv_obj_t * ui_auton_1_btn;
void ui_event_auton_2_btn(lv_event_t * e);
extern lv_obj_t * ui_auton_2_btn;
void ui_event_auton_3_btn(lv_event_t * e);
extern lv_obj_t * ui_auton_3_btn;
extern lv_obj_t * ui_auton_1_label;
extern lv_obj_t * ui_auton_2_label;
extern lv_obj_t * ui_auton_3_label;
extern lv_obj_t * ui_selected_auton;
// SCREEN: ui_debug
void ui_debug_screen_init(void);
extern lv_obj_t * ui_debug;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_page_selector2;
void ui_event_debug_button2(lv_event_t * e);
extern lv_obj_t * ui_debug_button2;
extern lv_obj_t * ui_logo2;
extern lv_obj_t * ui_team_number2;
void ui_event_auton_button2(lv_event_t * e);
extern lv_obj_t * ui_auton_button2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_debug_png);    // assets/Debug.png
LV_IMG_DECLARE(ui_img_steamed_png);    // assets/steamed.png
LV_IMG_DECLARE(ui_img_auton_png);    // assets/Auton.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
