// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: screen

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void alliance_changed(lv_event_t * e);
void auton_1_selected(lv_event_t * e);
void auton_2_selected(lv_event_t * e);
void auton_3_selected(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
